# Site wide configuration

title: Trevor Sullivan
description: >
  Personal website and blog for Trevor Sullivan, linguist and software engineer 
  at the University of Arizona. 
logo: logo2-1small.png # 120x120 px default image used for Twitter summary card
teaser: logo2-1small.png # 400x250 px default teaser image used in image archive grid
locale: en
# url: http://localhost:4000
url: http://trevortds.github.io

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist


# Octopress configuration

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: article
page_layout: article

# Format titles with titlecase?
titlecase: true


# Site owner
owner: 
  name: Trevor Sullivan
  web: http://trevortds.github.io
  email: Trevortds@gmail.com
  twitter:
  google: 
    ad-client:
    ad-slot:
  bio: >
    Trevor is a student of human language technology at the University of Arizona. 
  avatar: profile1small.jpg # 160x160 px image for author byline
  disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
